name: Build (and deploy)
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ARM_ENVIRONMENT: public
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  AZURE_TFSTATE_RESOURCE_GROUP: ${{ secrets.AZURE_TFSTATE_RESOURCE_GROUP }}
  AZURE_TFSTATE_STORAGE_ACCOUNT: ${{ secrets.AZURE_TFSTATE_STORAGE_ACCOUNT }}
  
jobs:
  terraform:
    name: Terraform Plan/Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./.infra
    outputs:
      app_insights_instrumentation_key: ${{ steps.tf_output.outputs.app_insights_instrumentation_key }}
      cat_game_app_service_name: ${{ steps.tf_output.outputs.cat_game_app_service_name }}
      dog_game_app_service_name: ${{ steps.tf_output.outputs.dog_game_app_service_name }}
      backend_api_func_app_name: ${{ steps.tf_output.outputs.backend_api_func_app_name }}
      backend_api_func_app_hostname: ${{ steps.tf_output.outputs.backend_api_func_app_hostname }}
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Terraform fmt
        id: fmt
        continue-on-error: true
        run: terraform fmt -check
      - name: Terraform Init
        id: init
        run: |
            terraform init \
              -backend-config "resource_group_name=${{ env.AZURE_TFSTATE_RESOURCE_GROUP }}" \
              -backend-config "storage_account_name=${{ env.AZURE_TFSTATE_STORAGE_ACCOUNT }}"
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform Import
        id: import
        continue-on-error: true
        run: |
          terraform import \
              -var "azure_resource_group_name=${{ env.AZURE_RESOURCE_GROUP }}" -lock=false \
              azurerm_resource_group.main_rg /subscriptions/${{ env.ARM_SUBSCRIPTION_ID }}/resourceGroups/${{ env.AZURE_RESOURCE_GROUP }}
      - name: Terraform Plan
        id: plan
        run: |
            terraform plan -no-color -lock=false -out=tfplan \
              -var "azure_resource_group_name=${{ env.AZURE_RESOURCE_GROUP }}"
      - name: Terraform Apply
        id: apply
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed')
        run: terraform apply -auto-approve -no-color tfplan
      - name: Terraform Output
        id: tf_output
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed')
        run: |
          echo "::set-output name=app_insights_instrumentation_key::$(terraform output -raw app_insights_instrumentation_key)"
          echo "::set-output name=cat_game_app_service_name::$(terraform output -raw cat_game_app_service_name)"
          echo "::set-output name=dog_game_app_service_name::$(terraform output -raw dog_game_app_service_name)"
          echo "::set-output name=backend_api_func_app_name::$(terraform output -raw backend_api_func_app_name)"
          echo "::set-output name=backend_api_func_app_hostname::$(terraform output -raw backend_api_func_app_hostname)"

  deploy-api:
    name: Build/Deploy Backend API
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build shared
        working-directory: ./shared
        run: |
            npm install
            npm run build
      - name: Build backend-api
        working-directory: ./backend-api
        run: |
            npm install
            npm run build
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ env.ARM_CLIENT_ID }}",
              "clientSecret": "${{ env.ARM_CLIENT_SECRET }}",
              "subscriptionId": "${{ env.ARM_SUBSCRIPTION_ID }}",
              "tenantId": "${{ env.ARM_TENANT_ID }}"
            }
      - run: |
          pushd ./backend-api
          zip -r ./backend-api.zip ./*
          popd
      - name: Deploy backend-api
        uses: Azure/functions-action@v1
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed')
        with:
          app-name: ${{ needs.terraform.outputs.backend_api_func_app_name }}
          package: ./backend-api/backend-api.zip

  deploy-apps:
    name: Build/Deploy Apps
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build shared
        working-directory: ./shared
        run: |
            npm install
            npm run build
      - name: Replace settings in cat-game
        uses: microsoft/variable-substitution@v1
        with:
          files: './cat-game/appsettings.json'
        env:
          backendApiBaseUrl: https://${{ needs.terraform.outputs.backend_api_func_app_hostname }}/
          appInsightsInstrumentationKey: https://${{ needs.terraform.outputs.app_insights_instrumentation_key }}/
      - name: Replace settings in dog-game
        uses: microsoft/variable-substitution@v1
        with:
          files: './dog-game/appsettings.json'
        env:
          backendApiBaseUrl: https://${{ needs.terraform.outputs.backend_api_func_app_hostname }}/
          appInsightsInstrumentationKey: https://${{ needs.terraform.outputs.app_insights_instrumentation_key }}/
      - name: Build cat-game
        working-directory: ./cat-game
        run: |
            npm install
            npm run build
      - name: Build dog-game
        working-directory: ./dog-game
        run: |
            npm install
            npm run build
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ env.ARM_CLIENT_ID }}",
              "clientSecret": "${{ env.ARM_CLIENT_SECRET }}",
              "subscriptionId": "${{ env.ARM_SUBSCRIPTION_ID }}",
              "tenantId": "${{ env.ARM_TENANT_ID }}"
            }
      - name: Deploy cat-game
        uses: azure/webapps-deploy@v2
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed')
        with:
          app-name: ${{ needs.terraform.outputs.cat_game_app_service_name }}
          package: ./cat-game/dist
      - name: Deploy dog-game
        uses: azure/webapps-deploy@v2
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed')
        with:
          app-name: ${{ needs.terraform.outputs.dog_game_app_service_name }}
          package: ./dog-game/dist
